#!/usr/bin/env bash
# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.
#
# Updates nanvix-version in .nanvix/nanvix.toml, commits to an
# automation branch, force-pushes, and opens (or refreshes) a PR.
#
# Required environment:
#   GH_TOKEN        — GitHub token with contents + pull-requests write.
#   LATEST_VERSION  — Version string to pin (e.g. 0.12.337).
#   LATEST_TAG      — Full release tag (e.g. v0.12.337).
#   REPO            — Owner/repo slug (e.g. nanvix/foo).

set -euo pipefail

TOML=".nanvix/nanvix.toml"
BRANCH="automation/update-nanvix-version"
COMMIT_MSG="[ci] E: Pin nanvix to ${LATEST_TAG}"

# Update the version in the TOML file (anchored to skip comments).
sed -i -E "s/^([[:space:]]*nanvix-version[[:space:]]*=[[:space:]]*\")[^\"]*/\1${LATEST_VERSION}/" "$TOML"

# Verify the substitution took effect.
if ! grep -qE "^[[:space:]]*nanvix-version[[:space:]]*=[[:space:]]*\"${LATEST_VERSION}\"" "$TOML"; then
	echo "::error::sed substitution failed — nanvix-version not updated in $TOML"
	exit 1
fi

git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"

git checkout -B "$BRANCH"
git add "$TOML"
git commit -m "$COMMIT_MSG"
git push origin "$BRANCH" --force

# Resolve default branch and open or refresh a PR.
DEFAULT_BRANCH=$(gh repo view "$REPO" --json defaultBranchRef \
	--jq '.defaultBranchRef.name')

PR_TITLE="[ci] E: Pin nanvix to ${LATEST_TAG}"
printf -v PR_BODY "%s\n\n%s" \
	"Automated bump of \`nanvix-version\` to [\`${LATEST_TAG}\`](https://github.com/nanvix/nanvix/releases/tag/${LATEST_TAG})." \
	"Generated by the [Nanvix CI](https://github.com/nanvix/workflows/blob/main/.github/workflows/nanvix-ci.yml) reusable workflow."

EXISTING_PR=$(gh pr list \
	--repo "$REPO" \
	--head "$BRANCH" \
	--base "$DEFAULT_BRANCH" \
	--state open \
	--json number \
	--jq '.[0].number // empty' 2>/dev/null || true)

if [ -n "$EXISTING_PR" ]; then
	gh pr edit "$EXISTING_PR" \
		--repo "$REPO" \
		--title "$PR_TITLE" \
		--body "$PR_BODY"
	echo "Updated existing PR #$EXISTING_PR."
else
	gh pr create \
		--repo "$REPO" \
		--title "$PR_TITLE" \
		--body "$PR_BODY" \
		--base "$DEFAULT_BRANCH" \
		--head "$BRANCH"
	echo "Opened new PR."
fi
