#!/usr/bin/env bash
set -euo pipefail

WORK_DIR="$(mktemp -d)"
BRANCH="automation/update-zutils-version"
COMMIT_MSG="[ci] E: Update zutils to ${LATEST_TAG}"

declare -a UPDATED_REPOS=()
declare -a SKIPPED_REPOS=()
declare -a FAILED_REPOS=()

# Process a single consumer repo. Returns 0 on success, 1 on failure.
# Called inside an `if !` context so set -e does not abort the
# script on failure; explicit `|| return 1` guards ensure the
# function signals errors back to the caller.
update_repo() {
    local REPO="$1"
    local REPO_DIR="$2"

    # Clone only the default branch (shallow).
    gh repo clone "$REPO" "$REPO_DIR" -- --depth 1 2>&1 || return 1

    pushd "$REPO_DIR" >/dev/null || return 1
    # Ensure we always return to the original directory.
    trap 'popd >/dev/null 2>&1 || true' RETURN

    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"

    local DEFAULT_BRANCH
    DEFAULT_BRANCH=$(gh repo view "$REPO" --json defaultBranchRef --jq '.defaultBranchRef.name')
    echo "Default branch: $DEFAULT_BRANCH"

    # Write/refresh `.zutils-version` pin file. This is the
    # single source of truth for consumers whose CI references
    # workflows@v2.1.0+
    echo "$LATEST_TAG" >.zutils-version
    # First clause: file tracked and modified vs. index.
    # Second clause: file untracked (first-time creation).
    if ! git diff --quiet -- .zutils-version 2>/dev/null ||
        ! git ls-files --error-unmatch .zutils-version >/dev/null 2>&1; then
        git add .zutils-version
        CHANGED=1
    fi

    # Copy bootstrapper templates from the release tarball.
    for TMPL in $BOOTSTRAPPER_TEMPLATES; do
        cp "${TEMPLATES_DIR}/${TMPL}" "${TMPL}" || return 1
        [ "${TMPL}" != "z.ps1" ] && { chmod +x "${TMPL}" || return 1; }
        if ! git diff --quiet -- "${TMPL}" ||
            ! git ls-files --error-unmatch "${TMPL}" >/dev/null 2>&1; then
            git add "${TMPL}"
            CHANGED=1
        fi
    done

    # Pin nanvix-version in .nanvix/nanvix.toml to the latest release.
    local TOML=".nanvix/nanvix.toml"
    if [ ! -f "$TOML" ]; then
        echo "missing required file: $TOML" >&2
        return 1
    fi

    local NANVIX_VERSION_MATCHES
    NANVIX_VERSION_MATCHES="$(grep -cE '^[[:space:]]*nanvix-version[[:space:]]*=[[:space:]]*"[^"]*"[[:space:]]*(#.*)?$' "$TOML")" || return 1
    if [ "$NANVIX_VERSION_MATCHES" -ne 1 ]; then
        echo "expected exactly one nanvix-version entry in $TOML, found $NANVIX_VERSION_MATCHES" >&2
        return 1
    fi

    sed -i -E "s/^([[:space:]]*nanvix-version[[:space:]]*=[[:space:]]*\")[^\"]*/\1${NANVIX_VERSION}/" "$TOML" || return 1

    local UPDATED_NANVIX_VERSION
    UPDATED_NANVIX_VERSION="$(sed -n -E 's/^[[:space:]]*nanvix-version[[:space:]]*=[[:space:]]*"([^"]*)"[[:space:]]*(#.*)?$/\1/p' "$TOML")" || return 1
    if [ "$UPDATED_NANVIX_VERSION" != "$NANVIX_VERSION" ]; then
        echo "failed to pin nanvix-version in $TOML to $NANVIX_VERSION" >&2
        return 1
    fi

    if ! git diff --quiet -- "$TOML"; then
        git add "$TOML"
        CHANGED=1
    fi

    if [ "$CHANGED" -eq 0 ]; then
        echo "$REPO already up to date."
        SKIPPED_REPOS+=("$REPO")
        return 0
    fi

    # Create or reset the automation branch and commit.
    git checkout -B "$BRANCH"
    git commit -m "$COMMIT_MSG"

    # Push using a one-off authenticated URL to avoid
    # persisting the token in .git/config.
    git push "https://x-access-token:${DISPATCH_TOKEN}@github.com/${REPO}.git" \
        "$BRANCH" --force 2>&1 || return 1

    # Open or refresh a PR.
    local PR_TITLE="[ci] Sync zutils ${LATEST_TAG}"
    local PR_BODY
    printf -v PR_BODY "%s\n%s\n%s\n%s\n\n%s" \
        "Automated sync with [\`${LATEST_TAG}\`](https://github.com/nanvix/zutils/releases/tag/${LATEST_TAG}):" \
        "- Pins \`.zutils-version\` to \`${LATEST_TAG}\` (source of truth on workflows@v2.1.0+)." \
        "- Copies bootstrapper templates (\`z\`, \`z.sh\`, \`z.ps1\`) from release assets." \
        "- Pins \`nanvix-version\` to \`${NANVIX_VERSION}\` in \`.nanvix/nanvix.toml\`." \
        "Generated by the [Update Zutils](https://github.com/nanvix/workflows/actions/workflows/nanvix-update-zutils.yml) workflow."

    local EXISTING_PR
    EXISTING_PR=$(gh pr list \
        --repo "$REPO" \
        --head "$BRANCH" \
        --base "$DEFAULT_BRANCH" \
        --state open \
        --json number \
        --jq '.[0].number // empty' 2>/dev/null || true)

    local NEW_PR=""
    if [ -n "$EXISTING_PR" ]; then
        gh pr edit "$EXISTING_PR" \
            --repo "$REPO" \
            --title "$PR_TITLE" \
            --body "$PR_BODY"
        echo "Updated existing PR #$EXISTING_PR on $REPO."
    else
        local PR_URL
        PR_URL=$(gh pr create \
            --repo "$REPO" \
            --title "$PR_TITLE" \
            --body "$PR_BODY" \
            --base "$DEFAULT_BRANCH" \
            --head "$BRANCH") || return 1

        NEW_PR="${PR_URL##*/}"
        echo "Opened PR #$NEW_PR on $REPO."
    fi

    # Best-effort assignment.
    local LATEST_PR="${EXISTING_PR:-$NEW_PR}"
    if [ -n "${LATEST_PR:-}" ] && [ -n "$ASSIGNEE" ]; then
        gh pr edit "$LATEST_PR" --repo "$REPO" \
            --add-assignee "$ASSIGNEE" \
            --add-reviewer "$ASSIGNEE" 2>/dev/null || true
    fi

    UPDATED_REPOS+=("$REPO")
}

for REPO in $(echo "$TARGET_REPOS" | jq -r '.[]'); do
    echo "::group::$REPO"
    REPO_DIR="$WORK_DIR/$(echo "$REPO" | tr '/' '-')"

    if ! update_repo "$REPO" "$REPO_DIR"; then
        echo "::warning::Failed to process $REPO; skipping."
        FAILED_REPOS+=("$REPO")
    fi

    echo "::endgroup::"
done

rm -rf "$WORK_DIR"

# Step summary.
{
    echo "## Update Zutils Version"
    echo ""
    echo "**Zutils tag:** \`$LATEST_TAG\`"
    echo "**Nanvix version:** \`$NANVIX_VERSION\`"

    if [ "${#UPDATED_REPOS[@]}" -gt 0 ]; then
        echo ""
        echo "### PRs opened or updated"
        for R in "${UPDATED_REPOS[@]}"; do echo "- $R"; done
    fi

    if [ "${#SKIPPED_REPOS[@]}" -gt 0 ]; then
        echo ""
        echo "### Already up to date"
        for R in "${SKIPPED_REPOS[@]}"; do echo "- $R"; done
    fi

    if [ "${#FAILED_REPOS[@]}" -gt 0 ]; then
        echo ""
        echo "### Failed"
        for R in "${FAILED_REPOS[@]}"; do echo "- $R"; done
    fi
} >>"$GITHUB_STEP_SUMMARY"
